name: fwdpy_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme
    - sphinx
    - gsl
    - nbsphinx
    - doxygen
    - pip:
        - numpy
        - matplotlib
        - ipython
        - cppimport
        - breathe
